### ISSUE TITLE
Gallery Notebooks

### ISSUE THREAD

**Issue by seesharprun** [AzureCosmosDB/CosmicWorks#14]
Would it make sense to eventually have gallery notebooks that import the CosmicWorks data?

For example, a Python notebook could look like this:

```python
import azure.cosmos
from azure.cosmos.partition_key import PartitionKey

database = cosmos_client.create_database_if_not_exists('CosmicWorks')
print('Database CosmicWorks created')

container = database.create_container_if_not_exists(id='Products', partition_key=PartitionKey(path='/categoryId'))
print('Container Products created')

%%upload --databaseName CosmicWorks --containerName Products --url https://raw.githubusercontent.com/AzureCosmosDB/CosmicWorks/master/data/cosmic-works-v4/product

%%sql --database CosmicWorks --container Products
SELECT p.name, p.sku, p.categoryName, p.price FROM products p
```

The user would import the notebook from the gallery, and then run all cells to import a dataset:

![image](https://user-images.githubusercontent.com/5067401/117212599-8ae10800-adc8-11eb-8e0f-df582e2d0158.png)

**Comment by markjbrown** [comment]
Given the longstanding unavailability for Cosmos Notebooks probably not. But can revisit this when Notebooks feature comes back online.

Thanks.
